### ISSUE TITLE
WC to support click tracking 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro#154]
# User story

As a developer, I want to be able to append click tracking to the auro-hyperlink, so I can meet the goals of my production work in regards to link tagging management.

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- [ ] Work with the tagging/tracking team to establish a reusable code pattern 
- [ ] Create Auro component that can wrap something like auro-hyperlink to support data collection

## Definition of “Done” (exit criteria)

> The story is generally “done” when the user can complete the outlined task, but make sure to define what that is.

This story will be considered complete once the auro-hyperlink has been updated to support a tagging plug-in scenario. 

#### Has been tested in all browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Edge (79 +)
- [ ] Safari
- [ ] Mobile Safari
- [ ] IE11

#### Accessibility and Performance 

- [ ] Chrome Lighthhouse report

**Comment by blackfalcon** [comment]
Work in progress. Spec discussed with stakeholders and developers for consistent use of WC proposal.
